name: Build C++ Executables

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Create build directory
        run: mkdir build

      - name: Compile C++ files (Windows)
        run: |
          for %f in (*.cpp) do cl /EHsc /Fe:build\%~nf.exe %f

      - name: Upload Windows executables
        uses: actions/upload-artifact@v4
        with:
          name: windows-executables
          path: build/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir build

      - name: Compile C++ files (macOS) with Clang
        run: |
          for file in *.cpp; do
            clang++ -std=c++17 -o build/"${file%.cpp}" "$file"
          done

      - name: Upload macOS executables
        uses: actions/upload-artifact@v4
        with:
          name: macos-executables
          path: build/
