name: Build C++ Executables

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Create build directory
        shell: pwsh
        run: New-Item -ItemType Directory -Path build-windows -Force

      - name: Compile C++ files (Windows)
        shell: pwsh
        run: |
          Get-ChildItem -Filter *.cpp | ForEach-Object {
            $exeName = "build-windows\" + $_.BaseName + ".exe"
            cl /EHsc /Fe:$exeName $_.FullName
          }

      - name: Commit and push build results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add build-windows
          git commit -m "Add Windows build artifacts [CI]"
          git push --force
        continue-on-error: true 
        
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir -p build-mac

      - name: Compile C++ files (macOS) with Clang
        run: |
          for file in *.cpp; do
            clang++ -std=c++17 -o build-mac/"${file%.cpp}" "$file"
          done

      - name: Commit and push build results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add build-mac
          git commit -m "Add macOS build artifacts [CI]"
          git push
        continue-on-error: true 
